### ISSUE TITLE
ArgoCD Notification script is out of date

### ISSUE THREAD

**Issue by ChampiYann** [Azure/gitops-connector#25]
The format for adding notifications to ArgoCD using ArgoCD Notifications is not up to date in the example from the README file.
Also it does not cover the case where the gitops connector is in a different namespace than ArgoCD itself.

I used this version in my own deployment.
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: <ARGOCD-NAMESPACE>
data:
  service.webhook.gitops-connector: |
    url: http://gitops-connector.<GITOPS-CONNECTOR-NAMESPACE>:8080/gitopsphase
    headers: #optional headers
    - name: Content-Type
      value: application/json
      
  template.sync-operation-status-change: |
    webhook:
      gitops-connector:
        method: POST
        body: |
          {
            "commitid": "{{.app.status.operationState.operation.sync.revision}}",
            "phase": "{{.app.status.operationState.phase}}",
            "sync_status": "{{.app.status.sync.status}}",
            "health": "{{.app.status.health.status}}",
            "message": "{{.app.status.operationState.message}}",
            "resources": {{toJson .app.status.resources}}
          }
  
  trigger.sync-operation-status: |
    - when: app.status.operationState.phase in ['Error', 'Failed']
      send: [sync-operation-status-change]
    - when: app.status.operationState.phase in ['Succeeded']
      send: [sync-operation-status-change]
    - when: app.status.operationState.phase in ['Running']
      send: [sync-operation-status-change]
    - when: app.status.health.status in ['Progressing']
      send: [sync-operation-status-change]
    - when: app.status.health.status in ['Healthy'] && app.status.operationState.phase in ['Succeeded']
      send: [sync-operation-status-change]
    - when: app.status.health.status in ['Unknown', 'Suspended', 'Degraded', 'Missing']
      send: [sync-operation-status-change]
  
  subscriptions: |
    - recipients:
        - gitops-connector:""
      triggers:
        - sync-operation-status
```
